---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: another-ldap-auth
  namespace: ingress-nginx
  labels:
    app: another-ldap-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: another-ldap-auth
  template:
    metadata:
      labels:
        app: another-ldap-auth
    spec:
      containers:
        - image: ghcr.io/scs-zke/another-ldap-auth:latest
          imagePullPolicy: Always
          name: another-ldap-auth
          ports:
            - name: http
              containerPort: 9000
          env:
            - name: LDAP_ENDPOINT
              value: "ldaps://ldapserver.example.org:636"
            - name: LDAP_MANAGER_DN_USERNAME
              value: "CN=john-service-user,OU=Administrators,DC=example,DC=org"
            - name: LDAP_SERVER_DOMAIN
              value: "example"
            - name: LDAP_SEARCH_BASE
              value: "DC=example,DC=org"
            - name: LDAP_SEARCH_FILTER
              value: "(sAMAccountName={username})"
            - name: TLS_ENABLED
              value: "false"
            - name: LOG_FORMAT
              value: "JSON"
            - name: LOG_LEVEL
              values: "INFO"
            - name: LDAP_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: another-ldap-auth
                  key: LDAP_MANAGER_PASSWORD
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 10001
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
